# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu1710"
    config.vm.provision "shell", path: "provision/node.sh", privileged: true

    # Managers
    (1..1).each do |number|
        config.vm.define "m#{number}" do |node|
            node.vm.network "public_network", ip: "192.168.178.20#{number}"
            node.vm.hostname = "m#{number}"
        end  
    end

    # Workers
    (1..3).each do |number|
        config.vm.define "w#{number}" do |node|
            node.vm.network "public_network", ip: "192.168.178.21#{number}"
            node.vm.hostname = "w#{number}"
        end  
    end

    config.vm.provider "hyperv" do |v|
        v.memory = 1028 
        v.cpus = 1
    end

end
